# Telegram bot
telegram:
  bot:
    token: 834692987:AAE9LuFuVYBj388YY_51wcrIJdURLHzcxSE
    name: karbo_node_bot
    notification:
      delay: 1000
server:
  port: 8087
timeout: 500
node:
  port: 32348
  cron: "0 0/5 * * * *"
  find:
    cron: "10 5 15 * * *"
    retry:
      days: 7

message:
  info: I can show you known Karbo nodes (Get button).nn You can add your node (Add button) and subscribe for the notification about availability, height, and version nnnn Also, I have REST endpoint with all active nodes nn https://node-monitor.cfapps.io/api/nodes nnnn Address for donate nn donate.rublin.org or nn KaAxHCPtJaFGDq4xLn3fASf3zVrAmqyE4359zn3r3deVjCeM3CYq7K4Y1pkfZkjfRd1W2VPXVZdA5RBdpc4Vzamo1H4F5qZ nnnn
spring:
  data:
    mongodb:
      username: java-node-bot
      password: jH6#2kurWZ1L
      host: ds231537.mlab.com
      port: 31537
      database: karbo-nodes
logging:
  file:
    max-history: 5
