# Telegram bot
telegram:
  bot:
    token: 834692987:AAE9LuFuVYBj388YY_51wcrIJdURLHzcxSE
    name: karbo_node_bot
server:
  port: 8087

node:
  port: 32348
spring:
  data:
    mongodb:
      username: java-node-bot
      password: jH6#2kurWZ1L
      host: ds231537.mlab.com
      port: 31537
      database: karbo-nodes